<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "bill".
 *
 * @property integer $id
 * @property string $description
 * @property double $amount
 * @property integer $categoryID
 * @property integer $payerID
 * @property integer $groupID
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\BillCategory $category
 * @property \common\models\Group $group
 * @property \common\models\User $payer
 * @property \common\models\BillParticipants[] $billParticipants
 * @property string $aliasModel
 */
abstract class Bill extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bill';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'updated_at',
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['amount'], 'double'],
            [['categoryID', 'amount', 'payerID', 'groupID'], 'required'],
            [['categoryID', 'payerID', 'groupID'], 'integer'],
            [['description'], 'string', 'max' => 255],
            [['created_at'], 'integer'],
            [['categoryID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\BillCategory::className(), 'targetAttribute' => ['categoryID' => 'id']],
            [['groupID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Group::className(), 'targetAttribute' => ['groupID' => 'id']],
            [['payerID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['payerID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'description' => 'Description',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'categoryID' => 'Category ID',
            'payerID' => 'Payer ID',
            'groupID' => 'Group ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\BillCategory::className(), ['id' => 'categoryID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(\common\models\Group::className(), ['id' => 'groupID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPayer()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'payerID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBillParticipants()
    {
        return $this->hasMany(\common\models\BillParticipants::className(), ['billID' => 'id']);
    }




}
