<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "billParticipants".
 *
 * @property integer $id
 * @property integer $billID
 * @property integer $participantID
 *
 * @property \common\models\Bill $bill
 * @property \common\models\User $participant
 * @property string $aliasModel
 */
abstract class BillParticipants extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'billParticipants';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['billID', 'participantID'], 'required'],
            [['billID', 'participantID'], 'integer'],
            [['billID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Bill::className(), 'targetAttribute' => ['billID' => 'id']],
            [['participantID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['participantID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'billID' => 'Bill ID',
            'participantID' => 'Participant ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBill()
    {
        return $this->hasOne(\common\models\Bill::className(), ['id' => 'billID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParticipant()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'participantID']);
    }




}
