<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "debt".
 *
 * @property integer $id
 * @property integer $firstPersonID
 * @property integer $secondPersonID
 * @property integer $groupID
 * @property string $amount
 *
 * @property \common\models\Group $group
 * @property \common\models\User $firstPerson
 * @property \common\models\User $secondPerson
 * @property string $aliasModel
 */
abstract class Debt extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'debt';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['firstPersonID', 'secondPersonID', 'groupID'], 'required'],
            [['firstPersonID', 'secondPersonID', 'groupID'], 'integer'],
            [['amount'], 'number'],
            [['groupID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Group::className(), 'targetAttribute' => ['groupID' => 'id']],
            [['firstPersonID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['firstPersonID' => 'id']],
            [['secondPersonID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['secondPersonID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'firstPersonID' => 'First Person ID',
            'secondPersonID' => 'Second Person ID',
            'groupID' => 'Group ID',
            'amount' => 'Amount',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(\common\models\Group::className(), ['id' => 'groupID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFirstPerson()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'firstPersonID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSecondPerson()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'secondPersonID']);
    }




}
