<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "eventParticipant".
 *
 * @property integer $id
 * @property integer $eventID
 * @property integer $userID
 *
 * @property \common\models\Event $event
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class EventParticipant extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'eventParticipant';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['eventID', 'userID'], 'required'],
            [['eventID', 'userID'], 'integer'],
            [['eventID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Event::className(), 'targetAttribute' => ['eventID' => 'id']],
            [['userID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['userID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'eventID' => 'Event ID',
            'userID' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'eventID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'userID']);
    }




}
