<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "group".
 *
 * @property integer $id
 * @property string $name
 * @property integer $isPersonal
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property \common\models\GroupMember[] $groupMembers
 * @property \common\models\ShoppingCategory[] $shoppingCategories
 * @property \common\models\ShoppingItem[] $shoppingItems
 * @property \common\models\ShoppingList[] $shoppingLists
 * @property string $aliasModel
 */
abstract class Group extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'group';
    }


    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => TimestampBehavior::className(),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['isPersonal'], 'integer'],
            [['name'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'isPersonal' => 'Is Personal',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroupMembers()
    {
        return $this->hasMany(\common\models\GroupMember::className(), ['groupID' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShoppingCategories()
    {
        return $this->hasMany(\common\models\ShoppingCategory::className(), ['groupID' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShoppingItems()
    {
        return $this->hasMany(\common\models\ShoppingItem::className(), ['groupID' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShoppingLists()
    {
        return $this->hasMany(\common\models\ShoppingList::className(), ['groupID' => 'id']);
    }




}
