<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "groupMember".
 *
 * @property integer $id
 * @property integer $groupID
 * @property integer $userID
 *
 * @property \common\models\Group $group
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class GroupMember extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'groupMember';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['groupID', 'userID'], 'required'],
            [['groupID', 'userID'], 'integer'],
            [['groupID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Group::className(), 'targetAttribute' => ['groupID' => 'id']],
            [['userID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['userID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'groupID' => 'Group ID',
            'userID' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGroup()
    {
        return $this->hasOne(\common\models\Group::className(), ['id' => 'groupID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'userID']);
    }




}
