<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "repeatableEvent".
 *
 * @property integer $id
 * @property string $type
 * @property integer $eventID
 * @property integer $originalEventID
 *
 * @property \common\models\Event $event
 * @property \common\models\Event $originalEvent
 * @property string $aliasModel
 */
abstract class RepeatableEvent extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'repeatableEvent';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'eventID', 'originalEventID'], 'required'],
            [['eventID', 'originalEventID'], 'integer'],
            [['type'], 'string', 'max' => 255],
            [['eventID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Event::className(), 'targetAttribute' => ['eventID' => 'id']],
            [['originalEventID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Event::className(), 'targetAttribute' => ['originalEventID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'eventID' => 'Event ID',
            'originalEventID' => 'Original Event ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'eventID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOriginalEvent()
    {
        return $this->hasOne(\common\models\Event::className(), ['id' => 'originalEventID']);
    }




}
