<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "shoppingListItem".
 *
 * @property integer $id
 * @property integer $shoppingListID
 * @property integer $shoppingItemID
 * @property string $reminder
 * @property integer $isChecked
 * @property string $nID
 *
 * @property \common\models\ShoppingItem $shoppingItem
 * @property \common\models\ShoppingList $shoppingList
 * @property string $aliasModel
 */
abstract class ShoppingListItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shoppingListItem';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shoppingListID', 'shoppingItemID'], 'required'],
            [['shoppingListID', 'shoppingItemID', 'isChecked'], 'integer'],
            [['reminder'], 'string', 'max' => 1023],
            [['nID'], 'string', 'max' => 255],
            [['shoppingItemID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ShoppingItem::className(), 'targetAttribute' => ['shoppingItemID' => 'id']],
            [['shoppingListID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\ShoppingList::className(), 'targetAttribute' => ['shoppingListID' => 'id']],
            [['nID'], 'safe']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'shoppingListID' => 'Shopping List ID',
            'shoppingItemID' => 'Shopping Item ID',
            'reminder' => 'Reminder',
            'isChecked' => 'Is Checked',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShoppingItem()
    {
        return $this->hasOne(\common\models\ShoppingItem::className(), ['id' => 'shoppingItemID']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getShoppingList()
    {
        return $this->hasOne(\common\models\ShoppingList::className(), ['id' => 'shoppingListID']);
    }




}
