<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "subscription".
 *
 * @property integer $id
 * @property string $type
 * @property string $data
 * @property integer $userID
 *
 * @property \common\models\User $user
 * @property string $aliasModel
 */
abstract class Subscription extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'subscription';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'userID'], 'required'],
            [['data'], 'string'],
            [['userID'], 'integer'],
            [['type'], 'string', 'max' => 255],
            [['userID'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\User::className(), 'targetAttribute' => ['userID' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'data' => 'Data',
            'userID' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\common\models\User::className(), ['id' => 'userID']);
    }




}
